
spring.application.name=web-security
#spring.profiles.active=dev
spring.datasource.url=jdbc:postgresql://ep-muddy-water-ai01blq8-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_jVXoLrgDR36l

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

# server.port=8085

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql


jwt.access-token-expiration=7200000
jwt.refresh-token-expiration=604800000
jwt.secretKey=asdfhads9f67as98dfyaisudhfa98s67dfy89aishudfuays89dfyasi8df7asdf87987g98a7sg986a89sdf7y